FROM ubuntu:16.04
LABEL maintainer="trenttfowler@gmail.com"
RUN apt install -y \
build-essential && \
gvm && \
#google cloud sdk
#ct transpiler
#
#git clone --branch v0.5.0 https://github.com/coreos/container-linux-config-transpiler
#cd container-linux-config-transpiler
#make
#
#matchbox
#quay
#ignition
#...